feat(base): Created the Movie model
forbaokhanh/sfmovies1 pull request #2
Opened 2017-05-23 22:40 UTC by tranthibaokhanh

Completed the 1-8 on the Build your own API tutorial: setting up the base as well as database design, migrations and models.

2017-05-23 23:48 UTC, itsachen requested changes
Could you add `.DS_Store` to your `.gitignore`? Just a couple of nits - could you reassign to me after?

2017-05-23 23:48 UTC, itsachen commented on .travis.yml
> +- npm run db:reset
Nit: Add a newline at the end of the file - its generally [good practice](https://stackoverflow.com/a/729795/659904) to have the last line in a file end in a newline character.

2017-05-23 23:48 UTC, itsachen commented on db/migrations/.eslintrc
> +}
Nit: Newline here

2017-05-23 23:48 UTC, itsachen commented on lib/models/movie.js
> +  serialize: function () {
Nit: Might want to standardize your tab sizes - in general we use 2 spaces for tabs.

2017-05-23 23:48 UTC, itsachen commented on lib/server.js
> +
Nit: Looks like theres an newline here

2017-05-23 23:48 UTC, itsachen commented on test/models/movie.test.js
> +'use '
Looks like this made its way into the PR before it was done?

2017-05-24 00:44 UTC, itsachen approved these changes
Just one remaining nit, other than that LGTM!

2017-05-24 00:44 UTC, itsachen commented on .travis.yml
> +
Nit: Missing newline

2017-05-24 17:11 UTC, sjl2 commented on .gitignore
> +
nit: extra line can be deleted.

2017-05-24 17:12 UTC, sjl2 commented on config/development.js
> +  PORT: 3000,
nit: alphabetize. Your text editor should have something that does this.

2017-05-24 17:12 UTC, sjl2 commented on config/test.js
> +  PORT: 3000,
nit: alphabetize

2017-05-24 17:14 UTC, sjl2 commented on package.json
> +    "db:migrate": "knex migrate:latest --knexfile db/index.js",
nit: alphabetize

2017-05-24 17:15 UTC, sjl2 commented on test/models/movie.test.js
> +        ]);
nit: I think the `]` is suppose to line up with `expect`, but I'm not 100%. @itsachen ??

2017-05-24 17:16 UTC, sjl2 approved these changes
LGTM with a couple nits!

2017-05-24 17:18 UTC, itsachen commented on test/models/movie.test.js
> +        ]);
👍 Yeah nice catch, it should line up

2017-05-24 18:17 UTC, merged